version: '3.8'

services:
  wordpress-db:
    image: mysql:8.0
    container_name: wp_database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lab-isolated-net

volumes:
  db_data:

networks:
  lab-isolated-net:
    external: true
