services:
  wordpress-db:
    image: mysql:8.0
    container_name: wp_database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lab-isolated-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    env_file:
      - .env
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - lab-isolated-net

  wordpress:
    image: wordpress:latest
    container_name: wp_frontend
    restart: unless-stopped
    depends_on:
      - wordpress-db
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - lab-isolated-net

volumes:
  db_data:
  wp_data:

networks:
  lab-isolated-net:
    external: true
